# DeluxeMenus 1.13.3-Release main configuration file
# 
# A full wiki on how to use this plugin can be found at:
# https://github.com/help-chat/DeluxeMenus/wiki

debug: false
check_updates: false
gui_menus:
  VoidReputation:
    file: /reputation/VoidReputation.yml
  Slayer:
    file: /professions/Slayer.yml
  Mining:
    file: /professions/Mining.yml
  Cooking:
    file: /professions/Cooking.yml
  Enchanting:
    file: /professions/Enchanting.yml
  Spellforging:
    file: /professions/Spellforging.yml
  Farming:
    file: /professions/Farming.yml
  FarmingPrestige:
    file: /professions/FarmingPrestige.yml
  ForagingPrestige:
    file: /professions/ForagingPrestige.yml
  MiningPrestige:
    file: /professions/MiningPrestige.yml
  SlayerPrestige:
    file: /professions/SlayerPrestige.yml
  SpellforgingPrestige:
    file: /professions/SpellforgingPrestige.yml
  EnchantingPrestige:
    file: /professions/EnchantingPrestige.yml
  Foraging:
    file: /professions/Foraging.yml
  Bosses:
    file: /main/Bosses.yml
  Main:
    file: /main/Main.yml
  Statistics:
    file: /main/Statistics.yml
  ResourceCollector:
    file: /main/ResourceCollector.yml
  MiningCollector:
    file: /resources/MiningCollector.yml
  FarmingCollector:
    file: /resources/FarmingCollector.yml
  ForagingCollector:
    file: /resources/ForagingCollector.yml
  SlayerCollector:
    file: /resources/SlayerCollector.yml
  DailyRewards:
    file: /main/DailyRewards.yml
  AlphaRank:
    file: /donate/AlphaRank.yml
  DonationShop:
    file: /donate/DonationShop.yml
  DonationRanks:
    file: /donate/DonationRanks.yml
  Settings:
    file: /main/Settings.yml
  ProfessionPrestiges:
    file: /battleTags/ProfessionPrestiges.yml
  ProfessionPrestiges2:
    file: /battleTags/ProfessionPrestiges2.yml
  BattleTags:
    file: /main/BattleTags.yml
  HomeSettings:
    file: /main/HomeSettings.yml
  AntiDrop:
    file: /main/AntiDrop.yml
  Achievements:
    file: /main/Achievements.yml
  Bounty:
    file: /main/Bounty.yml
  Profile:
    file: /main/Profile.yml
  Professions:
    file: /main/Professions.yml
  ProfessionPrestige:
    file: /main/ProfessionPrestige.yml
  Reputation:
    file: /main/Reputation.yml
  Map:
    file: /map/Map.yml
  Social:
    file: /main/Social.yml
  Minemap:
    file: /map/Minemap.yml
  Quests:
    file: /main/Quests.yml
  Minequests:
    file: Minequests.yml
  Enchanter:
    file: /shop/Enchanter.yml
  Jenny:
    file: /shop/Jenny.yml
  SlayerShop:
    file: /shop/SlayerShop.yml
  BakerShop:
    file: /shop/BakerShop.yml
  ForagerShop:
    file: /shop/ForagerShop.yml
  FarmerShop:
    file: /shop/FarmerShop.yml
  SpellforgerShop:
    file: /shop/SpellforgerShop.yml
  Weatherman:
    file: /shop/Weatherman.yml
  MinerMenu:
    file: /NPC/MinerMenu.yml
  Testmenu:
    file: Testmenu.yml
  TestShop:
    file: /shop/TestShop.yml
  Knowledge:
    file: /main/Knowledge.yml
  Leaderboards:
    file: Leaderboards.yml
  Forestmap:
    file: /map/Forestmap.yml
  FastTravel:
    file: /map/FastTravel.yml
  Dryad:
    file: /boss/Dryad.yml
  THFarmer:
    file: /NPCDisplay/THFarmer.yml
  THUHunter:
    file: /NPCDisplay/THUHunter.yml
  THUndead:
    file: /NPCDisplay/THUndead.yml
  THDemon:
    file: /NPCDisplay/THDemon.yml
