# DeluxeMenus 1.13.3-Release main configuration file
# 
# A full wiki on how to use this plugin can be found at:
# https://github.com/help-chat/DeluxeMenus/wiki

debug: false
check_updates: false
gui_menus:
  VoidReputation:
    file: /reputation/VoidReputation.yml
  FarmingPrestige:
    file: /professions/FarmingPrestige.yml
  ForagingPrestige:
    file: /professions/ForagingPrestige.yml
  MiningPrestige:
    file: /professions/MiningPrestige.yml
  SlayerPrestige:
    file: /professions/SlayerPrestige.yml
  SpellforgingPrestige:
    file: /professions/SpellforgingPrestige.yml
  EnchantingPrestige:
    file: /professions/EnchantingPrestige.yml
  ProfessionPrestiges:
    file: /battleTags/ProfessionPrestiges.yml
  ProfessionPrestiges2:
    file: /battleTags/ProfessionPrestiges2.yml
  BattleTags:
    file: /main/BattleTags.yml
  HomeSettings:
    file: /main/HomeSettings.yml
  Achievements:
    file: /main/Achievements.yml
  Bounty:
    file: /main/Bounty.yml
  ProfessionPrestige:
    file: /main/ProfessionPrestige.yml
  Quests:
    file: /main/Quests.yml
  Minequests:
    file: Minequests.yml
  Testmenu:
    file: Testmenu.yml
  TestShop:
    file: /shop/TestShop.yml
  Castle_Defense:
    file: /defense/Castle_Defense.yml
  Castle_Boosters:
    file: /defense/Castle_Boosters.yml
  Castle_Rewards:
    file: /defense/Castle_Rewards.yml
