PRISONER:
  location: Spawn, 77.5, 24.55, -605.5
  lines:
  - '&c&lPrisoner:'
  - '&aDavina'
PRISONER2:
  location: Spawn, 69.5, 24.55, -607.5
  lines:
  - '&c&lPrisoner:'
  - '&aTim'
PRISONER3:
  location: Spawn, 111.5, 24.55, -610.5
  lines:
  - '&c&lPrisoner:'
  - '&eAuction Master'
Reaper:
  location: Spawn, -96.115, 16.200, 176.668
  lines:
  - '{medium}&cReaper &fwill spawn in &a%sp_timer_Reaper%'
VoidWither:
  location: Spawn, -237.383, 51.200, -1228.843
  lines:
  - '{medium}&cVoid Wither &fwill spawn in &a%sp_timer_HellWither%'
Ghastly:
  location: Spawn, -151.727, 13.200, -1170.453
  lines:
  - '{medium}&cGhastly &fwill spawn in &a%sp_timer_GHAST_BOSS%'
Bullbo:
  location: Spawn, -176.700, 32.425, -1008.365
  lines:
  - '{medium}&cBullbo & Bulblin &fwill spawn in &a%sp_timer_VOID_BULBLIN%'
VoidMagma:
  location: Spawn, -152.524, 30.262, -1242.456
  lines:
  - '{medium}&cVoid Magma &fwill spawn in &a%sp_timer_HellVoidMagma%'
VoidDracula:
  location: Spawn, -91.503, 26.200, -1243.510
  lines:
  - '{medium}&cVoid Dracula &fwill spawn in &a%sp_timer_mVoidDracula1%'
GoblinChief:
  location: Spawn, -906.590, 31.200, -216.560
  lines:
  - '{medium}&cGoblin Chief &fwill spawn in &a%sp_timer_eGoblinChief%'
Bank:
  location: Spawn, -31.300, 18.5, -49.532
  lines:
  - '&e&l⛂ BANK ⛂'
Enchanter:
  location: Spawn, -42.5, 17.5, -12.5
  lines:
  - '&5&k⛂ &d&lEnchanter &5&k⛂'
Silver_Stool:
  location: Spawn, -157.5, 17.5, 145.5
  lines:
  - '&r&k⛂ &c&lSilver Stool &r&k⛂'
