display:
    name: 'Human'

options:
    default: true
    display: false
    off-combat-health-regen: false
    off-combat-mana-regen: false

# Must match an existing exp curve filename from the 'expcurves' folder
exp-curve: levels
max-level: 10

# Experience sources for main class experience.
main-exp-sources:

triggers:
#MAIN LEVEL UP
#     level-up-2:
#     - 'message{format="&eYou leveled up to: &aLevel %mmocore_level%&e!"}' 
#     - 'message{format="&eYou earned &a&l2x Attribute Points&e, redeem this by using &a/attributes&e!"}' 
#     - 'mmskill{id="MMOCORE_LEVEL_UP_MAIN"}'
#     - 'command{format="lp user %player% permission set level2 true"}'
#     - 'command{format="mmocore admin attribute-points give %player% 2"}'
#     level-up-3:
#     - 'message{format="&eYou leveled up to: &aLevel %mmocore_level%&e!"}' 
#     - 'message{format="&eYou earned &a&l1x Attribute Point&e, redeem this by using &a/attributes&e!"}' 
#     - 'mmskill{id="MMOCORE_LEVEL_UP_MAIN"}'
#     - 'command{format="lp user %player% permission set level3 true"}'
#     - 'command{format="mmocore admin attribute-points give %player% 1"}'    
#     level-up-4:
#     - 'message{format="&eYou leveled up to: &aLevel %mmocore_level%&e!"}' 
#     - 'message{format="&eYou earned &a&l1x Attribute Point&e, redeem this by using &a/attributes&e!"}' 
#     - 'mmskill{id="MMOCORE_LEVEL_UP_MAIN"}'
#     - 'command{format="lp user %player% permission set level4 true"}'
#     - 'command{format="mmocore admin attribute-points give %player% 1"}'
#     level-up-5:
#     - 'message{format="&eYou leveled up to: &aLevel %mmocore_level%&e!"}' 
#     - 'message{format="&eYou earned &a&l1x Attribute Point&e, & &aAccess to &cHell &eredeem this by using &a/attributes&e!"}' 
#     - 'message{format="&aYou have gained access to the &5&lVoid&a!"}' 
#     - 'mmskill{id="MMOCORE_LEVEL_UP_MAIN"}'
#     - 'command{format="lp user %player% permission set level5 true"}'
#     - 'command{format="mmocore admin attribute-points give %player% 1"}'
#     level-up-6:
#     - 'message{format="&eYou leveled up to: &aLevel %mmocore_level%&e!"}' 
#     - 'message{format="&eYou earned &a&l1x Attribute Point&e, redeem this by using &a/attributes&e!"}' 
#     - 'mmskill{id="MMOCORE_LEVEL_UP_MAIN"}'
#     - 'command{format="lp user %player% permission set level6 true"}'
#     - 'command{format="mmocore admin attribute-points give %player% 1"}'
#     level-up-7:
#     - 'message{format="&eYou leveled up to: &aLevel %mmocore_level%&e!"}' 
#     - 'message{format="&eYou earned &a&l1x Attribute Point&e, redeem this by using &a/attributes&e!"}' 
#     - 'mmskill{id="MMOCORE_LEVEL_UP_MAIN"}'
#     - 'command{format="lp user %player% permission set level7 true"}'
#     - 'command{format="mmocore admin attribute-points give %player% 1"}'
#     level-up-8:
#     - 'message{format="&eYou leveled up to: &aLevel %mmocore_level%&e!"}' 
#     - 'message{format="&eYou earned &a&l1x Attribute Point&e, redeem this by using &a/attributes&e!"}' 
#     - 'mmskill{id="MMOCORE_LEVEL_UP_MAIN"}'
#     - 'command{format="lp user %player% permission set level8 true"}'
#     - 'command{format="mmocore admin attribute-points give %player% 1"}'
#     level-up-9:
#     - 'message{format="&eYou leveled up to: &aLevel %mmocore_level%&e!"}' 
#     - 'message{format="&eYou earned &a&l1x Attribute Point&e, redeem this by using &a/attributes&e!"}' 
#     - 'mmskill{id="MMOCORE_LEVEL_UP_MAIN"}'
#     - 'command{format="lp user %player% permission set level9 true"}'
#     - 'command{format="mmocore admin attribute-points give %player% 1"}'
#     level-up-10:
#     - 'message{format="&eYou leveled up to: &aLevel %mmocore_level%&e!"}' 
#     - 'message{format="&eYou earned &a&l1x Attribute Point&e & &a&l1x Attribute Reset Token&e, redeem these by using &a/attributes&e!"}' 
#     - 'mmskill{id="MMOCORE_LEVEL_UP_MAIN"}'
#     - 'command{format="lp user %player% permission set level10 true"}'
#     - 'command{format="mmocore admin attribute-points give %player% 1"}'
#     - 'command{format="mmocore admin attr-realloc-points give %player% 1"}'

# #SLAYER TRIGGER
#     level-up-slayer-2:
#     - 'message{format="&eYou leveled up &c&lSlayer &eto: &aLevel %mmocore_profession_slayer%&e!"}' 
#     - 'command{format="lp user %player% permission set slayer2 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-slayer-3:
#     - 'message{format="&eYou leveled up &c&lSlayer &eto: &aLevel %mmocore_profession_slayer%&e!"}' 
#     - 'command{format="lp user %player% permission set slayer3 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-slayer-4:
#     - 'message{format="&eYou leveled up &c&lSlayer &eto: &aLevel %mmocore_profession_slayer%&e!"}' 
#     - 'command{format="lp user %player% permission set slayer4 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-slayer-5:
#     - 'message{format="&eYou leveled up &c&lSlayer &eto: &aLevel %mmocore_profession_slayer%&e!"}' 
#     - 'command{format="lp user %player% permission set slayer5 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-slayer-6:
#     - 'message{format="&eYou leveled up &c&lSlayer &eto: &aLevel %mmocore_profession_slayer%&e!"}' 
#     - 'command{format="lp user %player% permission set slayer6 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-slayer-7:
#     - 'message{format="&eYou leveled up &c&lSlayer &eto: &aLevel %mmocore_profession_slayer%&e!"}' 
#     - 'command{format="lp user %player% permission set slayer7 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-slayer-8:
#     - 'message{format="&eYou leveled up &c&lSlayer &eto: &aLevel %mmocore_profession_slayer%&e!"}' 
#     - 'command{format="lp user %player% permission set slayer8 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-slayer-9:
#     - 'message{format="&eYou leveled up &c&lSlayer &eto: &aLevel %mmocore_profession_slayer%&e!"}' 
#     - 'command{format="lp user %player% permission set slayer9 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-slayer-10:
#     - 'message{format="&eYou leveled up &c&lSlayer &eto: &aLevel %mmocore_profession_slayer%&e!"}' 
#     - 'command{format="lp user %player% permission set slayer10 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'

# #FARMING TRIGGER
#     level-up-Farming-2:
#     - 'message{format="&eYou leveled up &a&lFarming &eto: &aLevel %mmocore_profession_farming%&e!"}' 
#     - 'command{format="lp user %player% permission set Farming2 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-Farming-3:
#     - 'message{format="&eYou leveled up &a&lFarming &eto: &aLevel %mmocore_profession_farming%&e!"}' 
#     - 'command{format="lp user %player% permission set Farming3 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-Farming-4:
#     - 'message{format="&eYou leveled up &a&lFarming &eto: &aLevel %mmocore_profession_farming%&e!"}' 
#     - 'command{format="lp user %player% permission set Farming4 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-Farming-5:
#     - 'message{format="&eYou leveled up &a&lFarming &eto: &aLevel %mmocore_profession_farming%&e!"}' 
#     - 'command{format="lp user %player% permission set Farming5 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-Farming-6:
#     - 'message{format="&eYou leveled up &a&lFarming &eto: &aLevel %mmocore_profession_farming%&e!"}' 
#     - 'command{format="lp user %player% permission set Farming6 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-Farming-7:
#     - 'message{format="&eYou leveled up &a&lFarming &eto: &aLevel %mmocore_profession_farming%&e!"}' 
#     - 'command{format="lp user %player% permission set Farming7 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-Farming-8:
#     - 'message{format="&eYou leveled up &a&lFarming &eto: &aLevel %mmocore_profession_farming%&e!"}' 
#     - 'command{format="lp user %player% permission set Farming8 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-Farming-9:
#     - 'message{format="&eYou leveled up &a&lFarming &eto: &aLevel %mmocore_profession_farming%&e!"}' 
#     - 'command{format="lp user %player% permission set Farming9 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'
#     level-up-Farming-10:
#     - 'message{format="&eYou leveled up &a&lFarming &eto: &aLevel %mmocore_profession_farming%&e!"}' 
#     - 'command{format="lp user %player% permission set Farming10 true"}'
#     - 'mmskill{id="MMOCORE_LEVEL_UP_PROFESSION"}'

# #FORAGING TRIGGER
#     level-up-Foraging-2:
#     - 'message{format="&eYou leveled up &2&lForaging &eto: &aLevel %mmocore_profession_Foraging%&e!"}' 
#     - 'command{format="lp user %player% permission set Foraging2 true"}'
#     level-up-Foraging-3:
#     - 'message{format="&eYou leveled up &2&lForaging &eto: &aLevel %mmocore_profession_Foraging%&e!"}' 
#     - 'command{format="lp user %player% permission set Foraging3 true"}'
#     level-up-Foraging-4:
#     - 'message{format="&eYou leveled up &2&lForaging &eto: &aLevel %mmocore_profession_Foraging%&e!"}' 
#     - 'command{format="lp user %player% permission set Foraging4 true"}'
#     level-up-Foraging-5:
#     - 'message{format="&eYou leveled up &2&lForaging &eto: &aLevel %mmocore_profession_Foraging%&e!"}' 
#     - 'command{format="lp user %player% permission set Foraging5 true"}'
#     level-up-Foraging-6:
#     - 'message{format="&eYou leveled up &2&lForaging &eto: &aLevel %mmocore_profession_Foraging%&e!"}' 
#     - 'command{format="lp user %player% permission set Foraging6 true"}'
#     level-up-Foraging-7:
#     - 'message{format="&eYou leveled up &2&lForaging &eto: &aLevel %mmocore_profession_Foraging%&e!"}' 
#     - 'command{format="lp user %player% permission set Foraging7 true"}'
#     level-up-Foraging-8:
#     - 'message{format="&eYou leveled up &2&lForaging &eto: &aLevel %mmocore_profession_Foraging%&e!"}' 
#     - 'command{format="lp user %player% permission set Foraging8 true"}'
#     level-up-Foraging-9:
#     - 'message{format="&eYou leveled up &2&lForaging &eto: &aLevel %mmocore_profession_Foraging%&e!"}' 
#     - 'command{format="lp user %player% permission set Foraging9 true"}'
#     level-up-Foraging-10:
#     - 'message{format="&eYou leveled up &2&lForaging &eto: &aLevel %mmocore_profession_Foraging%&e!"}' 
#     - 'command{format="lp user %player% permission set Foraging10 true"}'

# #MINING TRIGGER
#     level-up-Mining-2:
#     - 'message{format="&eYou leveled up &9&lMining &eto: &aLevel %mmocore_profession_Mining%&e!"}' 
#     - 'command{format="lp user %player% permission set Mining2 true"}'
#     level-up-Mining-3:
#     - 'message{format="&eYou leveled up &9&lMining &eto: &aLevel %mmocore_profession_Mining%&e!"}' 
#     - 'command{format="lp user %player% permission set Mining3 true"}'
#     level-up-Mining-4:
#     - 'message{format="&eYou leveled up &9&lMining &eto: &aLevel %mmocore_profession_Mining%&e!"}' 
#     - 'command{format="lp user %player% permission set Mining4 true"}'
#     level-up-Mining-5:
#     - 'message{format="&eYou leveled up &9&lMining &eto: &aLevel %mmocore_profession_Mining%&e!"}' 
#     - 'command{format="lp user %player% permission set Mining5 true"}'
#     level-up-Mining-6:
#     - 'message{format="&eYou leveled up &9&lMining &eto: &aLevel %mmocore_profession_Mining%&e!"}' 
#     - 'command{format="lp user %player% permission set Mining6 true"}'
#     level-up-Mining-7:
#     - 'message{format="&eYou leveled up &9&lMining &eto: &aLevel %mmocore_profession_Mining%&e!"}' 
#     - 'command{format="lp user %player% permission set Mining7 true"}'
#     level-up-Mining-8:
#     - 'message{format="&eYou leveled up &9&lMining &eto: &aLevel %mmocore_profession_Mining%&e!"}' 
#     - 'command{format="lp user %player% permission set Mining8 true"}'
#     level-up-Mining-9:
#     - 'message{format="&eYou leveled up &9&lMining &eto: &aLevel %mmocore_profession_Mining%&e!"}' 
#     - 'command{format="lp user %player% permission set Mining9 true"}'
#     level-up-Mining-10:
#     - 'message{format="&eYou leveled up &9&lMining &eto: &aLevel %mmocore_profession_Mining%&e!"}' 
#     - 'command{format="lp user %player% permission set Mining10 true"}'

# #ENCHANTING TRIGGER
#     level-up-Enchanting-2:
#     - 'message{format="&eYou leveled up &d&lEnchanting &eto: &aLevel %mmocore_profession_Enchanting%&e!"}' 
#     - 'command{format="lp user %player% permission set Enchanting2 true"}'
#     level-up-Enchanting-3:
#     - 'message{format="&eYou leveled up &d&lEnchanting &eto: &aLevel %mmocore_profession_Enchanting%&e!"}' 
#     - 'command{format="lp user %player% permission set Enchanting3 true"}'
#     level-up-Enchanting-4:
#     - 'message{format="&eYou leveled up &d&lEnchanting &eto: &aLevel %mmocore_profession_Enchanting%&e!"}' 
#     - 'command{format="lp user %player% permission set Enchanting4 true"}'
#     level-up-Enchanting-5:
#     - 'message{format="&eYou leveled up &d&lEnchanting &eto: &aLevel %mmocore_profession_Enchanting%&e!"}' 
#     - 'command{format="lp user %player% permission set Enchanting5 true"}'
#     level-up-Enchanting-6:
#     - 'message{format="&eYou leveled up &d&lEnchanting &eto: &aLevel %mmocore_profession_Enchanting%&e!"}' 
#     - 'command{format="lp user %player% permission set Enchanting6 true"}'
#     level-up-Enchanting-7:
#     - 'message{format="&eYou leveled up &d&lEnchanting &eto: &aLevel %mmocore_profession_Enchanting%&e!"}' 
#     - 'command{format="lp user %player% permission set Enchanting7 true"}'
#     level-up-Enchanting-8:
#     - 'message{format="&eYou leveled up &d&lEnchanting &eto: &aLevel %mmocore_profession_Enchanting%&e!"}' 
#     - 'command{format="lp user %player% permission set Enchanting8 true"}'
#     level-up-Enchanting-9:
#     - 'message{format="&eYou leveled up &d&lEnchanting &eto: &aLevel %mmocore_profession_Enchanting%&e!"}' 
#     - 'command{format="lp user %player% permission set Enchanting9 true"}'
#     level-up-Enchanting-10:
#     - 'message{format="&eYou leveled up &d&lEnchanting &eto: &aLevel %mmocore_profession_Enchanting%&e!"}' 
#     - 'command{format="lp user %player% permission set Enchanting10 true"}'

# #SPELLFORGING TRIGGER
#     level-up-Spellforging-2:
#     - 'message{format="&eYou leveled up &5&lSpellforging &eto: &aLevel %mmocore_profession_Spellforging%&e!"}' 
#     - 'command{format="lp user %player% permission set Spellforging2 true"}'
#     level-up-Spellforging-3:
#     - 'message{format="&eYou leveled up &5&lSpellforging &eto: &aLevel %mmocore_profession_Spellforging%&e!"}' 
#     - 'command{format="lp user %player% permission set Spellforging3 true"}'
#     level-up-Spellforging-4:
#     - 'message{format="&eYou leveled up &5&lSpellforging &eto: &aLevel %mmocore_profession_Spellforging%&e!"}' 
#     - 'command{format="lp user %player% permission set Spellforging4 true"}'
#     level-up-Spellforging-5:
#     - 'message{format="&eYou leveled up &5&lSpellforging &eto: &aLevel %mmocore_profession_Spellforging%&e!"}' 
#     - 'command{format="lp user %player% permission set Spellforging5 true"}'
#     level-up-Spellforging-6:
#     - 'message{format="&eYou leveled up &5&lSpellforging &eto: &aLevel %mmocore_profession_Spellforging%&e!"}' 
#     - 'command{format="lp user %player% permission set Spellforging6 true"}'
#     level-up-Spellforging-7:
#     - 'message{format="&eYou leveled up &5&lSpellforging &eto: &aLevel %mmocore_profession_Spellforging%&e!"}' 
#     - 'command{format="lp user %player% permission set Spellforging7 true"}'
#     level-up-Spellforging-8:
#     - 'message{format="&eYou leveled up &5&lSpellforging &eto: &aLevel %mmocore_profession_Spellforging%&e!"}' 
#     - 'command{format="lp user %player% permission set Spellforging8 true"}'
#     level-up-Spellforging-9:
#     - 'message{format="&eYou leveled up &5&lSpellforging &eto: &aLevel %mmocore_profession_Spellforging%&e!"}' 
#     - 'command{format="lp user %player% permission set Spellforging9 true"}'
#     level-up-Spellforging-10:
#     - 'message{format="&eYou leveled up &5&lSpellforging &eto: &aLevel %mmocore_profession_Spellforging%&e!"}' 
#     - 'command{format="lp user %player% permission set Spellforging10 true"}'

# #Cooking TRIGGER
#     level-up-Cooking-2:
#     - 'message{format="&eYou leveled up &6&lCooking &eto: &aLevel %mmocore_profession_Cooking%&e!"}' 
#     - 'command{format="lp user %player% permission set Cooking2 true"}'
#     level-up-Cooking-3:
#     - 'message{format="&eYou leveled up &6&lCooking &eto: &aLevel %mmocore_profession_Cooking%&e!"}' 
#     - 'command{format="lp user %player% permission set Cooking3 true"}'
#     level-up-Cooking-4:
#     - 'message{format="&eYou leveled up &6&lCooking &eto: &aLevel %mmocore_profession_Cooking%&e!"}' 
#     - 'command{format="lp user %player% permission set Cooking4 true"}'
#     level-up-Cooking-5:
#     - 'message{format="&eYou leveled up &6&lCooking &eto: &aLevel %mmocore_profession_Cooking%&e!"}' 
#     - 'command{format="lp user %player% permission set Cooking5 true"}'
#     level-up-Cooking-6:
#     - 'message{format="&eYou leveled up &6&lCooking &eto: &aLevel %mmocore_profession_Cooking%&e!"}' 
#     - 'command{format="lp user %player% permission set Cooking6 true"}'
#     level-up-Cooking-7:
#     - 'message{format="&eYou leveled up &6&lCooking &eto: &aLevel %mmocore_profession_Cooking%&e!"}' 
#     - 'command{format="lp user %player% permission set Cooking7 true"}'
#     level-up-Cooking-8:
#     - 'message{format="&eYou leveled up &6&lCooking &eto: &aLevel %mmocore_profession_Cooking%&e!"}' 
#     - 'command{format="lp user %player% permission set Cooking8 true"}'
#     level-up-Cooking-9:
#     - 'message{format="&eYou leveled up &6&lCooking &eto: &aLevel %mmocore_profession_Cooking%&e!"}' 
#     - 'command{format="lp user %player% permission set Cooking9 true"}'
#     level-up-Cooking-10:
#     - 'message{format="&eYou leveled up &6&lCooking &eto: &aLevel %mmocore_profession_Cooking%&e!"}' 
#     - 'command{format="lp user %player% permission set Cooking10 true"}'