#Whenever a vanilla Iron Axe is converted, a random MI
#from the list will be selected to replace it.
#The number after the MMOItems name is the weighted chance.
#The chances of getting a Butcher Axe or Bone Cracker are
#higher than the chances of getting a Skull Breaker
  
#Format is "MATERIAL_TO_REPLACE: MMOITEMSTYPE.MMOITEM?WEIGHT"
#(However, weight only matters when using multiple conversion options)

#BRICK: MATERIAL.STEEL_INGOT, will make every brick (crafted, smelted or picked up)
#turn into the MMOItems Steel Ingot.
convert-on:
  pickup: true
  craft: true
  smelt: true

#Keep vanilla enchantments when converting?
keepEnchants: true
#Keep custom item name when converting?
keepDisplayName: true

Items:
  WOODEN_SWORD: SWORD.WOODEN_SWORD
  STONE_SWORD: SWORD.STONE_SWORD
  GOLDEN_SWORD: SWORD.GOLDEN_SWORD
  IRON_SWORD: SWORD.IRON_SWORD
  DIAMOND_SWORD: SWORD.DIAMOND_SWORD
  DIAMOND_HELMET: ARMOR.DIAMOND_HELMET
  DIAMOND_CHESTPLATE: ARMOR.DIAMOND_CHESTPLATE
  DIAMOND_LEGGINGS: ARMOR.DIAMOND_LEGGINGS
  DIAMOND_BOOTS: ARMOR.DIAMOND_BOOTS
  IRON_HELMET: ARMOR.IRON_HELMET
  IRON_CHESTPLATE: ARMOR.IRON_CHESTPLATE
  IRON_LEGGINGS: ARMOR.IRON_LEGGINGS
  IRON_BOOTS: ARMOR.IRON_BOOTS
  CHAINMAIL_HELMET: ARMOR.CHAINMAIL_HELMET
  CHAINMAIL_CHESTPLATE: ARMOR.CHAINMAIL_CHESTPLATE
  CHAINMAIL_LEGGINGS: ARMOR.CHAINMAIL_LEGGINGS
  CHAINMAIL_BOOTS: ARMOR.CHAINMAIL_BOOTS
  LEATHER_HELMET: ARMOR.LEATHER_HELMET
  LEATHER_CHESTPLATE: ARMOR.LEATHER_CHESTPLATE
  LEATHER_LEGGINGS: ARMOR.LEATHER_LEGGINGS
  LEATHER_BOOTS: ARMOR.LEATHER_BOOTS
  GOLDEN_HELMET: ARMOR.GOLDEN_HELMET
  GOLDEN_CHESTPLATE: ARMOR.GOLDEN_CHESTPLATE
  GOLDEN_LEGGINGS: ARMOR.GOLDEN_LEGGINGS
  GOLDEN_BOOTS: ARMOR.GOLDEN_BOOTS
  DIAMOND_PICKAXE: TOOL.DIAMOND_PICKAXE
  DIAMOND_SHOVEL: TOOL.DIAMOND_SHOVEL
  DIAMOND_AXE: TOOL.DIAMOND_AXE
  DIAMOND_HOE: TOOL.DIAMOND_HOE
  IRON_PICKAXE: TOOL.IRON_PICKAXE
  IRON_SHOVEL: TOOL.IRON_SHOVEL
  IRON_AXE: TOOL.IRON_AXE
  IRON_HOE: TOOL.IRON_HOE
  GOLDEN_PICKAXE: TOOL.GOLDEN_PICKAXE
  GOLDEN_SHOVEL: TOOL.GOLDEN_SHOVEL
  GOLDEN_AXE: TOOL.GOLDEN_AXE
  GOLDEN_HOE: TOOL.GOLDEN_HOE
  STONE_PICKAXE: TOOL.STONE_PICKAXE
  STONE_SHOVEL: TOOL.STONE_SHOVEL
  STONE_AXE: TOOL.STONE_AXE
  STONE_HOE: TOOL.STONE_HOE
  WOODEN_PICKAXE: TOOL.WOODEN_PICKAXE
  WOODEN_SHOVEL: TOOL.WOODEN_SHOVEL
  WOODEN_AXE: TOOL.WOODEN_AXE
  WOODEN_HOE: TOOL.WOODEN_HOE
  ENCHANTING_TABLE: MATERIAL.NULL
  ANVIL: MATERIAL.NULL
  LOOM: MATERIAL.NULL
  SMOKER: MATERIAL.NULL
  BLAST_FURNACE: MATERIAL.NULL
  FLETCHING_TABLE: MATERIAL.NULL
  GRINDSTONE: MATERIAL.NULL
  SMITHING_TABLE: MATERIAL.NULL
  STONECUTTER: MATERIAL.NULL
  CARTOGRAPHY_TABLE: MATERIAL.NULL
  SHIELD: MATERIAL.NULL
