#  __  __ _____ _____            _                       ___
# |  \/  |_   _|  __ \          | |                     |__ \
# | \  / | | | | |__) |___ _ __ | | __ _  ___ ___ _ __     ) |
# | |\/| | | | |  _  // _ \ '_ \| |/ _` |/ __/ _ \ '__|   / /
# | |  | |_| |_| | \ \  __/ |_) | | (_| | (_|  __/ |     / /_
# |_|  |_|_____|_|  \_\___| .__/|_|\__,_|\___\___|_|    |____|
#                         | |  by ASangarin
#                         |_|
# Config Version: 2.1
# Spigot: https://www.spigotmc.org/resources/mireplacer-requires-mmoitems.70961/
Options:
  # When enabled, stores the whole config into memory for performance.
  # Is highly recommended, but may take up some RAM if using a VERY large config.
  # NOTE: Some features will not work as intended and may be entirely disabled if
  # this is set to false. ONLY do this as a last resort if MIReplacer is lagging!
  cacheConfig: true
  # List of worlds that uses MIReplacer. Leave empty to use it server-wide.
  # worldList: ["world", "world_nether", "world_the_end"]
  worldList: []
  # Whether converted items should keep old enchantments once converted.
  keepEnchantments: true
  # Whether custom names carry over from old items once converted.
  keepCustomNames: true
  # The item name of the random item displayed when using weights in crafting.
  previewItemName: "{itemname}"
  # {itemname} will be replaced by the name of the possible item.
  previewItemIndex: "{itemname}"
  # The lore to display when previewing items to be crafted.
  # set to 'craftingLorePreview: []' to disable this feature.
  craftingLorePreview: []
  # MIReplacer will only convert items that contains a
  # line in their lore which DOES NOT match the given regex
  # Setting this to empty will convert ALL items with lore.
  # MIReplacer will ALWAYS convert vanilla items without lore.
  loreMatcher: ""
  # MIReplacer will only convert items with display
  # names that DOES NOT match the given regex
  # Setting this to empty will convert ALL items with display names.
  # MIReplacer will ALWAYS convert vanilla items without a display name.
  nameMatcher: ""
  # If an item contains any of these NBTTags it will not be converted
  # 'MMOITEMS_ITEM_TYPE' is pretty important as it will
  # prevent existing MMOItems from being converted.
  # 'RpgWorth' is for MMOCore currency items.
  # 'DoNotConvert' is a custom NBTTag which could be applied.
  exemptNBTTags: ["MMOITEMS_ITEM_TYPE", "RpgWorth", "DoNotConvert"]
  # Only turn to false if you'd like Slimefun items to convert.
  # This does nothing regardless of value if Slimefun isn't installed.
  exemptSlimefun: true

Convert-On:
  # Convert items when picked up from the ground
  pickup: true
  # Convert items when crafted in the crafting table
  craft: true
  # Convert items when smelted in a furnace. (Blast & Smokers on 1.14+)
  # !!! IMPORTANT: Servers must be restarted when changing the config
  # !!! for smelted recipes to work correctly when replacing!
  smelt: false
  # Convert items when smithed in a smithing table
  smithing: false
  # Convert when chests are being opened. This only applied once per
  # individual chest/minecart (resets on server restarts)
  chest: false
  # Convert when item is moved around in the inventory.
  # This one will call A LOT of events and therefore may not
  # be suited for larger servers. Most of the time there won't
  # even be the need for it, so best to leave it off.
  inventory-change: false

ConversionItems:
  WOODEN_SWORD: SWORD.WOODENSWORD
  STONE_SWORD: SWORD.STONESWORD
  GOLDEN_SWORD: SWORD.DIAMONDSWORD
  IRON_SWORD: SWORD.IRONSWORD
  DIAMOND_SWORD: SWORD.DIAMONDSWORD
  DIAMOND_HELMET: ARMOR.DIAMONDHELMET
  DIAMOND_CHESTPLATE: ARMOR.DIAMONDCHESTPLATE
  DIAMOND_LEGGINGS: ARMOR.DIAMONDLEGGINGS
  DIAMOND_BOOTS: ARMOR.DIAMONDBOOTS
  IRON_HELMET: ARMOR.IRONHELMET
  IRON_CHESTPLATE: ARMOR.IRONCHESTPLATE
  IRON_LEGGINGS: ARMOR.IRONLEGGINGS
  IRON_BOOTS: ARMOR.IRONBOOTS
  CHAINMAIL_HELMET: ARMOR.CHAINMAILHELMET
  CHAINMAIL_CHESTPLATE: ARMOR.CHAINMAILCHESTPLATE
  CHAINMAIL_LEGGINGS: ARMOR.CHAINMAILLEGGINGS
  CHAINMAIL_BOOTS: ARMOR.CHAINMAILBOOTS
  LEATHER_HELMET: ARMOR.LEATHERHELMET
  LEATHER_CHESTPLATE: ARMOR.LEATHERCHESTPLATE
  LEATHER_LEGGINGS: ARMOR.LEATHERLEGGINGS
  LEATHER_BOOTS: ARMOR.LEATHERBOOTS
  GOLDEN_HELMET: ARMOR.GOLDENHELMET
  GOLDEN_CHESTPLATE: ARMOR.GOLDENCHESTPLATE
  GOLDEN_LEGGINGS: ARMOR.GOLDENLEGGINGS
  GOLDEN_BOOTS: ARMOR.GOLDENBOOTS
  DIAMOND_PICKAXE: TOOL.DIAMOND_PICKAXE
  DIAMOND_SHOVEL: TOOL.DIAMOND_SHOVEL
  DIAMOND_AXE: TOOL.DIAMOND_AXE
  DIAMOND_HOE: TOOL.DIAMOND_HOE
  IRON_PICKAXE: TOOL.IRON_PICKAXE
  IRON_SHOVEL: TOOL.IRON_SHOVEL
  IRON_AXE: TOOL.IRON_AXE
  IRON_HOE: TOOL.IRON_HOE
  GOLDEN_PICKAXE: TOOL.GOLDEN_PICKAXE
  GOLDEN_SHOVEL: TOOL.GOLDEN_SHOVEL
  GOLDEN_AXE: TOOL.GOLDEN_AXE
  GOLDEN_HOE: TOOL.GOLDEN_HOE
  STONE_PICKAXE: TOOL.STONE_PICKAXE
  STONE_SHOVEL: TOOL.STONE_SHOVEL
  STONE_AXE: TOOL.STONE_AXE
  STONE_HOE: TOOL.STONE_HOE
  WOODEN_PICKAXE: TOOL.WOODEN_PICKAXE
  WOODEN_SHOVEL: TOOL.WOODEN_SHOVEL
  WOODEN_AXE: TOOL.WOODEN_AXE
  WOODEN_HOE: TOOL.WOODEN_HOE
  ENCHANTING_TABLE: MATERIAL.NULL
  ANVIL: MATERIAL.NULL
  LOOM: MATERIAL.NULL
  SMOKER: MATERIAL.NULL
  BLAST_FURNACE: MATERIAL.NULL
  FLETCHING_TABLE: MATERIAL.NULL
  GRINDSTONE: MATERIAL.NULL
  SMITHING_TABLE: MATERIAL.NULL
  STONECUTTER: MATERIAL.NULL
  CARTOGRAPHY_TABLE: MATERIAL.NULL
  SHIELD: MATERIAL.NULL
