# Here you can create your own disguises and disguise into them using the normal disguise commands
# To create them is super simple, you're using it just like you would in a command. The only tricky thing is that it must be valid yaml. TIP: Enclose the strings in '
# Please note that this is parsed exactly like a command, no spaces in your playername. Bypass by quoting with "!
# 
# You can use /grabskin <Target> <Optional Name> - To get the skin data from a file, another player or website.
# /savedisguise ingame will save a custom disguise in this config, including skin data.
# You can also provide a file or url for 'setSkin'! Just as you would for /grabskin.
# The setSkin argument will be automatically done for all /savedisguise usages, this way the skin never changes.
# /copydisguise <Optional Target Name/UUID> will give you the disguise in a usable string
# 
# You can also use placeholders in the disguises to create disguises that have the command users skin
# 
# %user-name% - Replaces %user-name% with the command user's name.
# %user-skin% - Replaces %user-skin% with the command user's skin for use with player disguises.
# 
# %target-name% - Finds first viable name from: Player name, entity custom nametag, then entity type (Pig, Horse, Cow)
# %target-skin% - If target is a player, replaces %target-skin% with their skin for use with player disguises
# If target is not a player, will silently fail
# 
# %held-item% - The currently held item in the main item slot
# %offhand-item% - The offhand item
# %armor% - The armor in <Item>,<Item>,<Item>,<Item> format
# %helmet% %chestplate% %leggings% %boots% - Obvious.
# These are best used in armor slots, or in settings that accept items. Can also be used alongside /copydisguise
# to get the string format of an item. By /disguise zombie setiteminmainhand %held-item% - Then /copydisguise.
# But the plugin will attempt to parse to the "simplest" format. So best used with an item that has more custom data
# than just the amount.
# 
# These can be used again for the 'target' by prepending 'target-' to the above. So %target-armor% %target-held-item%
# 
#  The below disguise would give a disguised sheep the nametag; Me: libraryaddict, Them: Sheep
#  Example: 'cow setCustomName "Me: %user-name%, Them: %target-name%"'
Disguises:
  libraryaddict: player VAMPIRE setArmor GOLDEN_BOOTS,GOLDEN_LEGGINGS,GOLDEN_CHESTPLATE,GOLDEN_HELMET
    setItemInMainHand WRITTEN_BOOK setGlowing setSkin {"id":"a149f81bf7844f8987c554afdd4db533","name":"libraryaddict","properties":[{"signature":"jB1QRLDAfDZToP6BhvGj2V01Q1d5jinr0Cwgm6Wu6QeuV2oYRHY9av9dVO7eN7qqUznmWaLJ6oTWbZdZERaD7LtnRSrAcB0DcBw+YonWL3EQj5nreS0FThBFYgkqf09PgeNMNSp+Ti8z9HbRaZKgPIcViCAGwY1fgsW2F9FL+VIape6zfYwWnoFV0/9HlvJl6lULBc7Uo56vqgRDmqn5LYyI7BS0lQQcx520pZIk7QPv7xsp8j8Bhe2SRWATwTmh2kn35nJJVQtemmLKotcycVb95pyWewJ4GTuhnXGPqoX9LzgMLRqjerDrnw5MxPd77NHYSLwTQsxgFZ9dnXrYYeLOaOCbUoEpTaORk5hktOaJOBijth+tAZu70sdzcuNn3jDeNFXA6h/LhJyDYZpO5jX5KpL/Fz+M1yhnIyGro+EZFxQiXpDnc9xVjipghO6xwTc1vJ2uTwB/pPXypISifBhrkIOaWTkzGWcIyhegd0N1irQgti7C1QJufOSxcYO3OcmEmoJn2vo65N/AXTYwUwzf1n+85Rto5boIrRXEkmE7oTuTvFKrBagQx2GPnMrejzv4GvX4NGmzc+W+9R+PvKqo2VDJJn8gCV9GaJOcBYGT0GnooR3cv/eiu8BTrRISmHj7TzRcpXH0maV2EjNM44JjXluPafvtSOb70gVNc7w=","name":"textures","value":"eyJ0aW1lc3RhbXAiOjE1MzQ2MDYzNjM1MTgsInByb2ZpbGVJZCI6IjQzYTgzNzNkNjQyOTQ1MTBhOWFhYjMwZjViM2NlYmIzIiwicHJvZmlsZU5hbWUiOiJTa3VsbENsaWVudFNraW42Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81ZGQwNWE5YjFkMWQwNzA1Yjk4NmJmYWRiNjA1YjYzNWNiNzNlZWMxYjAwNDdhZTgwNjgwODEwNDExNzI2NmMwIn19fQ=="}]}
  WASP: bee setBaby false setHasStung true setHasStung true
  QUEEN_BEE: bee setBaby false setGlowColor YELLOW setGlowing true setHasNectar true
    setHasStung true
