# default config.yml for ConsoleSpamFix
# config version 1.8.1

#Add here the messages you want to hide from your console and logs.
#Each line represents a new message.
#NOTE! You dont need to add the full message!
#The plugin will hide all messages that contain the text added below.
#  EXAMPLE:
#
#    Messages-To-Hide-Filter:
#    - 'WARNING: unlocalizedName'
#
#  All messages that will appear in the server console that contain these words 'WARNING: unlocalizedName' will be hidden and they will not appear on logs or console.
#  If you have large errors you dont have to type the full error. But the more words you add the more accurate will be and will not hide other messages that may contain the words added in the filter.

Messages-To-Hide-Filter:
- 'Exception thrown whilst handling event: org.bukkit.event.player.PlayerInteractEvent'
- 'at io.lumine.mythicenchants.profiles.EnchantsProfileManager.updatePlayerWeapon(EnchantsProfileManager.java:149)'
- "Ignored advancement 'minecraft:story/iron_tools' in progress file"
- "org.bukkit.command.CommandException: Unhandled exception executing command 'itemjoin' in plugin ItemJoin v5.1.0-RELEASE-b545"
- "generated an exception while executing task 2814"
- "Message event will be REMOVED! Usage in package"
- "lumine.mythicenchants.profiles.EnchantsProfileManager.lambda"
#Chat messages with color and format codes support.
#Minecraft Color and Format Codes: http://minecraft.gamepedia.com/Formatting_codes    
ChatMessages:
    NoPermission: '&4[System] &cYou don''t have permission!'
    CmdHelp: '&4[System] &cAvailable commands:&6 /csf reload'
    CmdReload: '&2[System] &aConfig reload complete!'

    
