# Lobby, Prison, Cell, Adventure, Home
Server: Adventure

# LuckPerms Context for auto-assigning permissions with correct Context
# Lobby, Prison, Adventure
Context: Adventure

# Should arrows be despawned after hitting an enemy, rather than remaining on the ground
Arrow-Despawn: true
