menu_title: '&f&l»&7&l» &8Settings &7&l«&f&l«'
open_command: Settings
update_interval: 1    
size: 44
items:
  'Decoration':
    material: BLACK_STAINED_GLASS_PANE		
    display_name: '&a'
    slots:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8    
    - 9    
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32 
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44

  'Back':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODY1MmUyYjkzNmNhODAyNmJkMjg2NTFkN2M5ZjI4MTlkMmU5MjM2OTc3MzRkMThkZmRiMTM1NTBmOGZkYWQ1ZiJ9fX0=
    slot: 40
    priority: 1
    display_name: '&aGo Back'
    right_click_commands:
    - "[openguimenu] main"
    left_click_commands:
    - "[openguimenu] main"

  'ImStuck':
    material: OAK_DOOR
    hide_attributes: true
    priority: 1
    slot: 10
    display_name: "&cIm Stuck"
    lore:
    - ''
    - '&7You will be teleported back to Spawn!'
    - ''
    - '&8&l» &eClick to Use'
    click_commands:
    - "[player] spawn"
    - "[close]"

  'SafeDrop':
    material: BUCKET
    hide_attributes: true
    priority: 1
    slot: 13
    display_name: '&aSafe Drop'
    lore:
    - ''
    - '&7Toggle your Safe Drop settings!'
    - ''
    - '&8&l» &eClick to View'
    click_commands:
    - "[openguimenu] AntiDrop"

  'TipsOn':
    material: OAK_SIGN
    hide_attributes: true
    priority: 1
    slot: 14
    view_requirement:
      requirements:
        Pex:
          type: has permission
          permission: Tips              
    display_name: '&aTips&f: &aON'
    lore:
    - ''
    - '&7Receive tips randomly in chat!'
    - ''
    - '&8&l» &eClick to Disable'
    click_commands:
    - "[console] lp user %player_name% permission set tips false"
    - "[message] &cTips will now be hidden from you in chat!"
    - "[refresh]"
  'TipsOff':
    material: DARK_OAK_SIGN
    hide_attributes: true
    priority: 2
    slot: 14
    view_requirement:
      requirements:
        Pex:
          type: "!has permission"
          permission: Tips              
    display_name: '&aTips&f: &aOFF'
    lore:
    - ''
    - '&7Receive tips randomly in chat!'
    - ''
    - '&8&l» &eClick to Enable'
    click_commands:
    - "[console] lp user %player_name% permission set tips true"
    - "[message] &aTips will now be displayed in chat every 90 seconds!"
    - "[refresh]"

  'ItemFilter':
    material: HOPPER
    hide_attributes: true
    priority: 1
    slot: 12
    display_name: '&aItem Filter'
    lore:
    - ''
    - '&7Filter items from being picked up!'
    - ''
    - '&8&l» &eClick to View'
    click_commands:
    - "[player] itemfilter"

  'Compass':
    material: COMPASS
    hide_attributes: true
    priority: 0
    slot: 11
    display_name: '&aQuest Compass'
    lore:
    - ''
    - '&8&l» &eLeft-Click to Enable Compass'
    - '&8&l» &eRight-Click to Disable Compass'
    left_click_commands:
    - "[player] calebcompass show"
    - "[message] &aYour compass has been enabled!"
    - "[close]"
    right_click_commands:
    - "[player] calebcompass hide"
    - "[message] &cYour compass has been hidden!"
    - "[close]"


  'RP_ON':
    material: PAINTING
    hide_attributes: true
    priority: 1
    slot: 15
    view_requirement:
      requirements:
        Pex:
          type: has permission
          permission: RP.DOWNLOAD              
    display_name: '&aResource Pack&f: &aENABLED'
    lore:
    - ''
    - '&7Download the Resource Pack upon logging in!'
    - ''
    - '&8&l» &eClick to Disable'
    click_commands:
    - "[player] rp disable"
    - "[refresh]"
  'RP_OFF':
    material: PAINTING
    hide_attributes: true
    priority: 2
    slot: 15
    view_requirement:
      requirements:
        Pex:
          type: "!has permission"
          permission: RP.DOWNLOAD              
    display_name: '&aResource Pack&f: &cDISABLED'
    lore:
    - ''
    - '&7Download the Resource Pack upon logging in!'
    - ''
    - '&8&l» &eClick to Enable'
    click_commands:
    - "[player] rp enable"
    - "[refresh]"


  'RemoveTag':
    material: BARRIER
    hide_attributes: true
    priority: 1
    slot: 16
    display_name: '&aReset Pre-Fix'
    lore:
    - ''
    - '&7Clears existing Pre-Fixes!'
    click_commands:
    - "[console] lp user %player_name% meta removeprefix 99"
    - "[message] &cCleared any exisiting Pre-Fixes!"
    - "[close]"

  'RemoveTag':
    material: BARRIER
    hide_attributes: true
    priority: 1
    slot: 16
    display_name: '&aReset Pre-Fix'
    lore:
    - ''
    - '&7Clears existing Pre-Fixes!'
    click_commands:
    - "[console] lp user %player_name% meta removeprefix 99"
    - "[message] &cCleared any exisiting Pre-Fixes!"
    - "[close]"

  'ResourceCollector':
    material: HOPPER_MINECART	
    hide_attributes: true
    priority: 1
    slot: 20
    display_name: "&cResource Collector"
    lore:
    - ''
    - '&7Automatically stores resources you pickup!'
    - '&7Use &a/Resources &7for quick access!'
    - ''
    - '&8&l» &eClick to View'
    click_commands:
    - "[openguimenu] ResourceCollector"

  'MUSIC_ON':
    material: JUKEBOX
    hide_attributes: true
    update: true
    priority: 1
    slot: 22
    view_requirement:
      requirements:
        Pex:
          type: has permission
          permission: Music.ON              
    display_name: '&aMusic ON'
    lore:
    - ''
    - '&aVolume: &7%anbs_player_song_volume%'
    - '&aProgress: &7%anbs_player_song_current_ticks%/%anbs_player_song_max_ticks%'
    - ''
    - '&8&l» &eLeft-Click to Turn Off'
    - '&8&l» &eRight-Click to Adjust Volume'
    left_click_commands:
    - "[player] music off"
    - "[close]"
    right_click_commands:
    - "[player] music volume"
    - "[close]"
  'MUSIC_OFF':
    material: JUKEBOX
    hide_attributes: true
    update: true
    priority: 0
    slot: 22
    view_requirement:
      requirements:
        Pex:
          type: "!has permission"
          permission: Music.ON              
    display_name: '&aMusic &cOFF'
    lore:
    - ''
    - '&aVolume: &7%anbs_player_song_volume%'
    - ''
    - '&8&l» &eLeft-Click to Turn On'
    - '&8&l» &eRight-Click to Adjust Volume'
    left_click_commands:
    - "[player] music on"
    - "[close]"
    right_click_commands:
    - "[player] music volume"
    - "[close]"

  'Battle_Tags':
    material: NAME_TAG
    hide_attributes: true
    priority: 1
    slot: 25
    display_name: '&aBattle Tags'
    lore:
    - ''
    - '&7You can earn &aBattle Tags &7while'
    - '&7adventuring and completing achievements!'
    - ''
    - '&8&l» &eClick to View'
    click_commands:
    - "[openguimenu] BattleTags"
    
  'AlphaTag':
    material: NAME_TAG
    hide_attributes: true
    priority: 0
    slot: 44
    view_requirement:
      requirements:
        Pex:
          type: has permission
          permission: Alpha.Rank              
    display_name: '&aUse Alpha Pre-Fix'
    lore:
    - ''
    - '&fChat Prefix: &6[&eAlpha&6]'
    click_commands:
    - "[console] lp user %player_name% meta setprefix 99 &6[&eAlpha&6]"
    - "[message] &aYou now have the &6[&eAlpha&6] &aPre-Fix!"
    - "[close]"

#THIRD ROW
