#
# SpawnerPlaceholders by Sek
#
# Written for Monzter
#
#

#
# Placeholder Format: %sp_timer_<spawner-name>%
#

# This is the first section of text in the generated placeholder.
# Requires a restart to change.
#
placeholder-prefix: 'sp'

# Set the plugin messages here.
#
messages:
  prefix: '&8[&9SpawnerPlaceholders&8] &r'
  plugin-reloaded: '&aSpawnerPlaceholders has been reloaded.'
  permission-denied: '&cNo permission.'
  unknown-command: '&cUnknown command.'
  spawner-mob-active: '&aMob Is Alive'
  waiting: '&7Waiting...'