# Welcome to SkBee

settings:
  debug: false
elements:
  nbt: true
  scoreboard: true
  recipe: true
  bound: true
  structure: true
  virtual-furnace: true
  text-component: true
  pathfinding: true
  world-creator: false
  auto-load-custom-worlds: true
recipe:
  namespace: skrecipe
