checkForUpdates: true
disablePlugin: false
useWorldGuard: true
usePackets: true
useHats: false
useDisguises: false
useRide: false
useInteractGUI: false
debug: false
combatTag: false
petPunch: true
useHopperGUI: true
combatMessage: '&4Your pet was removed because you engaged in a fight with another
  player.'
handlePlayerData: false
PetExtraRemoval: true
runGUIAsync: true
perPetName: true
hideDisguisedPlayers: true
animationRefreshRate: 2
disallowDisguiseTeleport: true
respawnPetOnWorldMove: true
SaveWithUUID: true
PetSpawnDistance: -3
PetNameLimit: 20
standardizedPermissions: false
dismountOnWater: false
downloadDefaultPetsIfNone: true
bypassSpawnProtections: false
minimumPetTeleportRange: 40.0
petTeleportCheckSeconds: 6.0
disallowedPetNameWords:
- GAMERS
- RISE
- UP
