#
# ██████╗░██╗░░░░░░█████╗░██╗░░░██╗███████╗██████╗░██╗███╗░░██╗███████╗░█████╗░
# ██╔══██╗██║░░░░░██╔══██╗╚██╗░██╔╝██╔════╝██╔══██╗██║████╗░██║██╔════╝██╔══██╗
# ██████╔╝██║░░░░░███████║░╚████╔╝░█████╗░░██████╔╝██║██╔██╗██║█████╗░░██║░░██║
# ██╔═══╝░██║░░░░░██╔══██║░░╚██╔╝░░██╔══╝░░██╔══██╗██║██║╚████║██╔══╝░░██║░░██║
# ██║░░░░░███████╗██║░░██║░░░██║░░░███████╗██║░░██║██║██║░╚███║██║░░░░░╚█████╔╝
# ╚═╝░░░░░╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝╚═╝░░╚══╝╚═╝░░░░░░╚════╝░
#                               Player Information
#                           Developed by aglerr with <3
#
# Join our discord to get a support!
# Discord: https://discord.gg/vHqQfsF
#
# If you found any bugs please report it on discussion page or join our discord
# server, don't post the bug on the review section!
# Don't forget to rate us ★★★★★
#
###############################################################################
messages:
  no-permission: '&6&l(!) &cNo permission!'
  reload: '&6&l(!) &aYou have reloaded the configuration.'
  disable-world: '&6&l(!) &cYou can''t use this feature on this world.'
  open: '&7You are now viewing &e%player_name%&7''s information.'
  target-not-found: '&6&l(!) &cPlayer not found!'
  help-cmd: 
  - '&6&l&nPlayerInformation - v2.8'
  - '&6/playerinfo view <player> &7- see any player''s information'
  - '&6/playerinfo reload &7- reload the configuration.'
  - '&6/playerinfo toggle &7- toggle on/off so other players can''t see your information.'
  toggle-blocked: 
  - '&7You have &cdisabled &7player information'
  toggle-enabled: 
  - '&7You have &aenabled &7player information'
  target-toggle-blocked: '&e%player_name% &7has his information &cprivate&7!'
  selfview: '&cYou can''t view your own information.'
  is-in-combat: '&cYou can''t view player information while in combat!'
  
options:
  shiftclick: true #If false, you don't need to sneak to open the player info.
  disable-npc: true #Disable viewing NPC's information.
  disable-selfviewing: false #Disable player from viewing their own info.
  disable-open-msg: true

hooks:
  combatlogx: false

# You can put 'disable-worlds: []' to disable this features.
# worlds name are case-sensitive
disable-worlds:

close-distance:
  enabled: false
  distance: 5
  messages:
    close: '&6&l(!) &e%player_name% &7is too far from you.'

# Interval in ticks
# 20 ticks = 1 second
# 100 ticks = 5 seconds
auto-refresh:
  enabled: true
  interval: 40

# Time in seconds
cooldown:
  enabled: false
  time: 3
  messages:
    on-cooldown: '&7You &ccan''t &7open &e%player_name%&7''s information for &6%time% seconds&7.'
    
# Latest: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sounds:
  on-open:
    enabled: true
    name: BLOCK_LAVA_POP
    volume: 10.0
    pitch: 1.0