version: v64
mysql:
  enabled: true
  host: localhost
  port: '3306'
  user: minecraft
  pass: kWz7Y8eK0tMCUvr0Cm
  base: minecraft_live
  prefix: betonquest_
language: en
update:
  enabled: false
  strategy: MINOR
  automatic: true
default_journal_slot: '7'
max_npc_distance: '4'
citizens_npcs_by_name: 'false'
default_conversation_IO: tellraw
default_interceptor: packet,simple
display_chat_after_conversation: 'true'
combat_delay: '5'
notify_pullback: 'true'
default_package: default
remove_items_after_respawn: 'true'
quest_items_unbreakable: 'true'
sounds:
  start: ENTITY_VILLAGER_AMBIENT
  end: ENTITY_VILLAGER_YES
  journal: ENTITY_BAT_TAKEOFF
  update: 'false'
  full: 'false'
cmd_blacklist:
- spawn
hook:
  citizens: 'true'
  mythicmobs: 'true'
  vault: 'true'
  worldguard: 'true'
  skript: 'true'
  mcmmo: 'true'
  effectlib: 'true'
  playerpoints: 'true'
  heroes: 'true'
  magic: 'true'
  denizen: 'true'
  skillapi: 'true'
  quests: 'true'
  shopkeepers: 'true'
  placeholderapi: 'true'
  holographicdisplays: 'true'
  racesandclasses: 'true'
  legendquest: 'true'
  worldedit: 'true'
  betonlangapi: 'true'
  bountifulapi: 'true'
  protocollib: 'true'
  brewery: 'true'
  jobs: 'true'
journal:
  chars_per_line: '19'
  lines_per_page: '13'
  one_entry_per_page: 'true'
  reversed_order: 'true'
  hide_date: 'true'
  full_main_page: 'true'
journal_colors:
  date:
    day: '9'
    hour: '6'
  line: '4'
  text: '0'
conversation_colors:
  npc: gold
  player: green
  text: gray
  answer: white
  number: yellow
  option: white
date_format: MM.dd.yyyy HH:mm
packages:
- default
- default
- default
- default
debug: 'false'
acceptNPCLeftClick: true
