configuration_version: v5
worlds:
  Homes:
    plot:
      height: 100
      size: 200
      filling: air
      floor: grass_block
      bedrock: true
      biome: minecraft:forest
      auto_merge: false
      create_signs: false
    wall:
      block: STONE_SLAB
      block_claimed: AIR
      filling: BARRIER
      height: 100
      place_top_block: true
    road:
      width: 100
      height: 100
      block: BARRIER
      flags: {}
    misc_spawn_unowned: false
    home:
      nonmembers: side
      default: side
    schematic:
      specify_on_claim: false
      on_claim: false
      file: 'null'
      schematics: []
    chat:
      forced: false
      enabled: true
    economy:
      prices:
        merge: 100000000000000
        sell: 100000000000000
        claim: 100000000000000
      use: false
    limits:
      max-members: 20
    world:
      max_height: 256
      gamemode: survival
      min_height: 1
      border: false
    event:
      spawn:
        egg: false
        breeding: false
        custom: true
    natural_mob_spawning: false
    mob_spawner_spawning: false
    flags: {}
